/**
 * Copyright (c) 2013-present Snowplow Analytics Ltd. All rights reserved.
 *
 * This software is made available by Snowplow Analytics, Ltd., under the terms of the Snowplow
 * Limited Use License Agreement, Version 1.1 located at
 * https://docs.snowplow.io/limited-use-license-1.1 BY INSTALLING, DOWNLOADING, ACCESSING, USING OR
 * DISTRIBUTING ANY PORTION OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.
 */
package com.snowplowanalytics.snowplow.bigquery

import cats.Id
import cats.effect.testing.specs2.CatsEffect
import cats.effect.{ExitCode, IO}
import com.comcast.ip4s.Port
import com.snowplowanalytics.iglu.core.SchemaCriterion
import com.snowplowanalytics.snowplow.streams.pubsub.{PubsubFactoryConfig, PubsubSinkConfig, PubsubSinkConfigM, PubsubSourceConfig}
import com.snowplowanalytics.snowplow.runtime.{Metrics => CommonMetrics}
import com.snowplowanalytics.snowplow.runtime.{AcceptedLicense, ConfigParser, HttpClient, Retrying, Sentry, Telemetry, Webhook}
import com.snowplowanalytics.snowplow.streams.compression.DecompressionConfig
import org.http4s.implicits.http4sLiteralsSyntax
import org.specs2.Specification

import java.nio.file.Paths
import scala.concurrent.duration.DurationInt

class PubsubConfigSpec extends Specification with CatsEffect {

  def is = s2"""
   Config parse should be able to parse
    minimal pubsub config $minimal
    extended pubsub config $extended
  """

  private def minimal =
    assert(
      resource = "/config.pubsub.minimal.hocon",
      expectedResult = Right(
        PubsubConfigSpec.minimalConfig
      )
    )

  private def extended =
    assert(
      resource = "/config.pubsub.reference.hocon",
      expectedResult = Right(
        PubsubConfigSpec.extendedConfig
      )
    )

  private def assert(
    resource: String,
    expectedResult: Either[ExitCode, Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig]]
  ) = {
    val path = Paths.get(getClass.getResource(resource).toURI)
    ConfigParser.configFromFile[IO, Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig]](path).value.map { result =>
      result must beEqualTo(expectedResult)
    }
  }
}

object PubsubConfigSpec {
  private val minimalConfig = Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig](
    input = PubsubSourceConfig(
      subscription            = PubsubSourceConfig.Subscription("my-project", "snowplow-enriched"),
      parallelPullFactor      = BigDecimal(0.5),
      durationPerAckExtension = 15.seconds,
      minRemainingAckDeadline = BigDecimal(0.1),
      maxMessagesPerPull      = 1000,
      debounceRequests        = 100.millis,
      streamingPull           = true,
      retries = PubsubSourceConfig.Retries(
        transientErrors = PubsubSourceConfig.TransientErrorRetrying(delay = 100.millis, attempts = 10)
      )
    ),
    output = Config.Output(
      good = Config.BigQuery(
        project     = "my-project",
        dataset     = "my-dataset",
        table       = "events",
        credentials = None
      ),
      bad = Config.SinkWithMaxSize(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("my-project", "snowplow-bad"),
          batchSize            = 1000,
          requestByteThreshold = 1000000,
          retries = PubsubSinkConfig.Retries(
            transientErrors = PubsubSinkConfig.TransientErrorRetrying(delay = 100.millis, attempts = 10)
          )
        ),
        maxRecordSize = 9000000
      )
    ),
    streams = PubsubFactoryConfig(None),
    batching = Config.Batching(
      maxBytes              = 10000000,
      maxDelay              = 1.second,
      writeBatchConcurrency = 2
    ),
    cpuParallelism = Config.CpuParallelism(
      parseBytesFactor = 0.1,
      transformFactor  = 0.75
    ),
    retries = Config.Retries(
      setupErrors     = Retrying.Config.ForSetup(delay = 30.seconds),
      transientErrors = Retrying.Config.ForTransient(delay = 1.second, attempts = 5),
      alterTableWait  = Config.AlterTableWaitRetries(delay = 1.second),
      tooManyColumns  = Config.TooManyColumnsRetries(delay = 5.minutes)
    ),
    telemetry = Telemetry.Config(
      disable         = false,
      collectorUri    = uri"https://collector-g.snowplowanalytics.com",
      userProvidedId  = None,
      autoGeneratedId = None,
      instanceId      = None,
      moduleName      = None,
      moduleVersion   = None
    ),
    monitoring = Config.Monitoring(
      metrics     = Config.Metrics(None, CommonMetrics.PrometheusConfig(Map.empty)),
      sentry      = None,
      healthProbe = Config.HealthProbe(port = Port.fromInt(8000).get, unhealthyLatency = 5.minutes),
      webhook     = Webhook.Config(endpoint = None, tags = Map.empty, heartbeat = 5.minutes)
    ),
    license                 = AcceptedLicense(),
    skipSchemas             = List.empty,
    legacyColumns           = List.empty,
    legacyColumnMode        = false,
    exitOnMissingIgluSchema = true,
    decompression           = DecompressionConfig(maxBytesInBatch = 5242880, maxBytesSinglePayload = 10000000),
    http                    = Config.Http(HttpClient.Config(4))
  )

  private val extendedConfig = Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig](
    input = PubsubSourceConfig(
      subscription            = PubsubSourceConfig.Subscription("my-project", "snowplow-enriched"),
      parallelPullFactor      = BigDecimal(0.5),
      durationPerAckExtension = 15.seconds,
      minRemainingAckDeadline = BigDecimal(0.1),
      maxMessagesPerPull      = 1000,
      debounceRequests        = 100.millis,
      streamingPull           = true,
      retries = PubsubSourceConfig.Retries(
        transientErrors = PubsubSourceConfig.TransientErrorRetrying(delay = 100.millis, attempts = 10)
      )
    ),
    output = Config.Output(
      good = Config.BigQuery(
        project     = "my-project",
        dataset     = "my-dataset",
        table       = "events",
        credentials = None
      ),
      bad = Config.SinkWithMaxSize(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("my-project", "snowplow-bad"),
          batchSize            = 100,
          requestByteThreshold = 1000000,
          retries = PubsubSinkConfig.Retries(
            transientErrors = PubsubSinkConfig.TransientErrorRetrying(delay = 100.millis, attempts = 10)
          )
        ),
        maxRecordSize = 9000000
      )
    ),
    streams = PubsubFactoryConfig(None),
    batching = Config.Batching(
      maxBytes              = 10000000,
      maxDelay              = 1.second,
      writeBatchConcurrency = 2
    ),
    cpuParallelism = Config.CpuParallelism(
      parseBytesFactor = 0.1,
      transformFactor  = 0.75
    ),
    retries = Config.Retries(
      setupErrors     = Retrying.Config.ForSetup(delay = 30.seconds),
      transientErrors = Retrying.Config.ForTransient(delay = 1.second, attempts = 5),
      alterTableWait  = Config.AlterTableWaitRetries(delay = 1.second),
      tooManyColumns  = Config.TooManyColumnsRetries(delay = 5.minutes)
    ),
    telemetry = Telemetry.Config(
      disable         = false,
      collectorUri    = uri"https://collector-g.snowplowanalytics.com",
      userProvidedId  = Some("my_pipeline"),
      autoGeneratedId = Some("hfy67e5ydhtrd"),
      instanceId      = Some("665bhft5u6udjf"),
      moduleName      = Some("bigquery-loader-vmss"),
      moduleVersion   = Some("1.0.0")
    ),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(
        statsd = Some(
          CommonMetrics.StatsdConfig(
            hostname = "127.0.0.1",
            port     = 8125,
            tags     = Map("myTag" -> "xyz"),
            period   = 1.minute,
            prefix   = "snowplow.bigquery.loader"
          )
        ),
        prometheus = CommonMetrics.PrometheusConfig(Map("myTag" -> "xyz"))
      ),
      sentry = Some(Sentry.ConfigM[Id](dsn = "https://public@sentry.example.com/1", environment = None, tags = Map("myTag" -> "xyz"))),
      healthProbe = Config.HealthProbe(
        port             = Port.fromInt(8000).get,
        unhealthyLatency = 5.minutes
      ),
      webhook = Webhook.Config(endpoint = Some(uri"https://webhook.acme.com"), tags = Map("pipeline" -> "production"), heartbeat = 1.hour)
    ),
    license = AcceptedLicense(),
    skipSchemas = List(
      SchemaCriterion.parse("iglu:com.acme/skipped1/jsonschema/1-0-0").get,
      SchemaCriterion.parse("iglu:com.acme/skipped2/jsonschema/1-0-*").get,
      SchemaCriterion.parse("iglu:com.acme/skipped3/jsonschema/1-*-*").get,
      SchemaCriterion.parse("iglu:com.acme/skipped4/jsonschema/*-*-*").get
    ),
    legacyColumns = List(
      SchemaCriterion.parse("iglu:com.acme/legacy/jsonschema/1-*-*").get,
      SchemaCriterion.parse("iglu:com.acme/legacy/jsonschema/2-*-*").get
    ),
    legacyColumnMode        = false,
    exitOnMissingIgluSchema = true,
    decompression           = DecompressionConfig(maxBytesInBatch = 5242880, maxBytesSinglePayload = 10000000),
    http                    = Config.Http(HttpClient.Config(4))
  )
}
